var DataSourceA=[
["1","1","aggresive_a.jpg","aggresive ","Animal","1","aggresive_a.jpg"],
["1","1","aggressive_h.jpg","aggressive ","Human","2","aggressive_h.jpg"],
["1","1","aggressive_o.jpg","aggressive ","Object","3","aggressive_o.jpg"],
["1","1","aggressive_p.jpg","aggressive ","Plant","4","aggressive_p.jpg"],
["1","1","aggressive_r.jpg","aggressive ","Robot","5","aggressive_r.jpg"],
["1","2","amazing_a.jpg","amazing ","Animal","1","amazing_a.jpg"],
["1","2","amazing_h.jpg","amazing ","Human","2","amazing_h.jpg"],
["1","2","amazing_o.jpg","amazing ","Object","3","amazing_o.jpg"],
["1","2","amazing_p.jpg","amazing ","Plant","4","amazing_p.jpg"],
["1","2","amazing_r.jpg","amazing ","Robot","5","amazing_r.jpg"],
["1","3","anxious_a.jpg","anxious","Animal","1","anxious_a.jpg"],
["1","3","anxious_h.jpg","anxious","Human","2","anxious_h.jpg"],
["1","3","anxious_o.jpg","anxious","Object","3","anxious_o.jpg"],
["1","3","anxious_p.jpg","anxious","Plant","4","anxious_p.jpg"],
["1","3","anxious_r.jpg","anxious","Robot","5","anxious_r.jpg"],
["1","4","awesome_a.jpg","awesome ","Animal","1","awesome_a.jpg"],
["1","4","awesome_h.jpg","awesome ","Human","2","awesome_h.jpg"],
["1","4","awesome_o.jpg","awesome ","Object","3","awesome_o.jpg"],
["1","4","awesome_p.jpg","awesome ","Plant","4","awesome_p.jpg"],
["1","4","awesome_r.jpg","awesome ","Robot","5","awesome_r.jpg"],
["1","5","basic_a.jpg","basic ","Animal","1","basic_a.jpg"],
["1","5","basic_h.jpg","basic ","Human","2","basic_h.jpg"],
["1","5","basic_o.jpg","basic ","Object","3","basic_o.jpg"],
["1","5","basic_p.jpg","basic ","Plant","4","basic_p.jpg"],
["1","5","basic_r.jpg","basic ","Robot","5","basic_r.jpg"],
["1","6","classic_a.jpg","classic ","Animal","1","classic_a.jpg"],
["1","6","classic_h.jpg","classic ","Human","2","classic_h.jpg"],
["1","6","classic_o.jpg","classic ","Object","3","classic_o.jpg"],
["1","6","classic_p.jpg","classic ","Plant","4","classic_p.jpg"],
["1","6","classic_r.jpg","classic ","Robot","5","classic_r.jpg"],
["1","7","cool_a.jpg","cool ","Animal","1","cool_a.jpg"],
["1","7","cool_h.jpg","cool ","Human","2","cool_h.jpg"],
["1","7","cool_o.jpg","cool ","Object","3","cool_o.jpg"],
["1","7","cool_p.jpg","cool ","Plant","4","cool_p.jpg"],
["1","7","cool_r.jpg","cool ","Robot","5","cool_r.jpg"],
["1","8","cute_a.jpg","cute ","Animal","1","cute_a.jpg"],
["1","8","cute_h.jpg","cute ","Human","2","cute_h.jpg"],
["1","8","cute_o.jpg","cute ","Object","3","cute_o.jpg"],
["1","8","cute_p.jpg","cute ","Plant","4","cute_p.jpg"],
["1","8","cute_r.jpg","cute ","Robot","5","cute_r.jpg"],
["1","9","extraordinairy_a.jpg","extraordinairy","Animal","1","extraordinairy_a.jpg"],
["1","9","extraordinairy_h.jpg","extraordinairy","Human","2","extraordinairy_h.jpg"],
["1","9","extraordinairy_o.jpg","extraordinairy","Object","3","extraordinairy_o.jpg"],
["1","9","extraordinairy_p.jpg","extraordinairy","Plant","4","extraordinairy_p.jpg"],
["1","9","extraordinairy_r.jpg","extraordinairy","Robot","5","extraordinairy_r.jpg"],
["1","10","fair_a.jpg","fair ","Animal","1","fair_a.jpg"],
["1","10","fair_h.jpg","fair ","Human","2","fair_h.jpg"],
["1","10","fair_o.jpg","fair ","Object","3","fair_o.jpg"],
["1","10","fair_p.jpg","fair ","Plant","4","fair_p.jpg"],
["1","10","fair_r.jpg","fair ","Robot","5","fair_r.jpg"],
["1","11","good_a.jpg","good","Animal","1","good_a.jpg"],
["1","11","good_h.jpg","good","Human","2","good_h.jpg"],
["1","11","good_o.jpg","good","Object","3","good_o.jpg"],
["1","11","good_p.jpg","good","Plant","4","good_p.jpg"],
["1","11","good_r.jpg","good","Robot","5","good_r.jpg"],
["1","12","great_a.jpg","great ","Animal","1","great_a.jpg"],
["1","12","great_h.jpg","great ","Human","2","great_h.jpg"],
["1","12","great_o.jpg","great ","Object","3","great_o.jpg"],
["1","12","great_p.jpg","great ","Plant","4","great_p.jpg"],
["1","12","great_r.jpg","great ","Robot","5","great_r.jpg"],
["1","13","handsome_a.jpg","handsome","Animal","1","handsome_a.jpg"],
["1","13","handsome_h.jpg","handsome","Human","2","handsome_h.jpg"],
["1","13","handsome_o.jpg","handsome","Object","3","handsome_o.jpg"],
["1","13","handsome_p.jpg","handsome","Plant","4","handsome_p.jpg"],
["1","13","handsome_r.jpg","handsome","Robot","5","handsome_r.jpg"],
["1","14","heavy_a.jpg","heavy ","Animal","1","heavy_a.jpg"],
["1","14","heavy_h.jpg","heavy ","Human","2","heavy_h.jpg"],
["1","14","heavy_o.jpg","heavy ","Object","3","heavy_o.jpg"],
["1","14","heavy_p.jpg","heavy ","Plant","4","heavy_p.jpg"],
["1","14","heavy_r.jpg","heavy ","Robot","5","heavy_r.jpg"],
["1","15","hot_a.jpg","hot ","Animal","1","hot_a.jpg"],
["1","15","hot_h.jpg","hot ","Human","2","hot_h.jpg"],
["1","15","hot_o.jpg","hot ","Object","3","hot_o.jpg"],
["1","15","hot_p.jpg","hot ","Plant","4","hot_p.jpg"],
["1","15","hot_r.jpg","hot ","Robot","5","hot_r.jpg"],
["1","16","huge_a.jpg","huge","Animal","1","huge_a.jpg"],
["1","16","huge_h.jpg","huge","Human","2","huge_h.jpg"],
["1","16","huge_o.jpg","huge","Object","3","huge_o.jpg"],
["1","16","huge_p.jpg","huge","Plant","4","huge_p.jpg"],
["1","16","huge_r.jpg","huge","Robot","5","huge_r.jpg"],
["1","17","ideal_a.jpg","ideal ","Animal","1","ideal_a.jpg"],
["1","17","ideal_h.jpg","ideal ","Human","2","ideal_h.jpg"],
["1","17","ideal_o.jpg","ideal ","Object","3","ideal_o.jpg"],
["1","17","ideal_p.jpg","ideal ","Plant","4","ideal_p.jpg"],
["1","17","ideal_r.jpg","ideal ","Robot","5","ideal_r.jpg"],
["1","18","impressive_a.jpg","impressive ","Animal","1","impressive_a.jpg"],
["1","18","impressive_h.jpg","impressive ","Human","2","impressive_h.jpg"],
["1","18","impressive_o.jpg","impressive ","Object","3","impressive_o.jpg"],
["1","18","impressive_p.jpg","impressive ","Plant","4","impressive_p.jpg"],
["1","18","impressive_r.jpg","impressive ","Robot","5","impressive_r.jpg"],
["1","19","interesting_a.jpg","interesting ","Animal","1","interesting_a.jpg"],
["1","19","interesting_h.jpg","interesting ","Human","2","interesting_h.jpg"],
["1","19","interesting_o.jpg","interesting ","Object","3","interesting_o.jpg"],
["1","19","interesting_p.jpg","interesting ","Plant","4","interesting_p.jpg"],
["1","19","interesting_r.jpg","interesting ","Robot","5","interesting_r.jpg"],
["1","20","lame_a.jpg","lame ","Animal","1","lame_a.jpg"],
["1","20","lame_h.jpg","lame ","Human","2","lame_h.jpg"],
["1","20","lame_o.jpg","lame ","Object","3","lame_o.jpg"],
["1","20","lame_p.jpg","lame ","Plant","4","lame_p.jpg"],
["1","20","lame_r.jpg","lame ","Robot","5","lame_r.jpg"],
["1","60","lame.jpg","lame","word","6","lame.jpg"],
["1","61","loud.jpg","loud","word","6","loud.jpg"],
["1","62","modern.jpg","modern","word","6","modern.jpg"],
["1","63","odd.jpg","odd","word","6","odd.jpg"],
["1","64","okay.jpg","okay","word","6","okay.jpg"],
["1","65","old.jpg","old","word","6","old.jpg"],
["1","66","ordinary.jpg","ordinary","word","6","ordinary.jpg"],
["1","67","peaceful.jpg","peaceful","word","6","peaceful.jpg"],
["1","68","plain.jpg","plain","word","6","plain.jpg"],
["1","69","quick.jpg","quick","word","6","quick.jpg"],
["1","70","radient.jpg","radient","word","6","radient.jpg"],
["1","71","rare.jpg","rare","word","6","rare.jpg"],
["1","72","small.jpg","small","word","6","small.jpg"],
["1","73","solid.jpg","solid","word","6","solid.jpg"],
["1","74","stunning.jpg","stunning","word","6","stunning.jpg"],
["1","75","sweet.jpg","sweet","word","6","sweet.jpg"],
["1","76","tall.jpg","tall","word","6","tall.jpg"],
["1","77","ugly.jpg","ugly","word","6","ugly.jpg"],
["1","78","weird.jpg","weird","word","6","weird.jpg"],
["1","79","wild.jpg","wild","word","6","wild.jpg"],
["1","81","filler1.jpg","filler","question","7","filler1.jpg"],
["1","82","filler2.jpg","filler","question","7","filler2.jpg"],
["1","83","filler3.jpg","filler","question","7","filler3.jpg"],
["1","84","filler4.jpg","filler","question","7","filler4.jpg"],
["1","85","filler5.jpg","filler","question","7","filler5.jpg"]
];

var DataSourceB=[
["2","21","loud_a.jpg","loud ","Animal","1","loud_a.jpg"],
["2","21","loud_h.jpg","loud ","Human","2","loud_h.jpg"],
["2","21","loud_o.jpg","loud ","Object","3","loud_o.jpg"],
["2","21","loud_p.jpg","loud ","Plant","4","loud_p.jpg"],
["2","21","loud_r.jpg","loud ","Robot","5","loud_r.jpg"],
["2","22","modern_a.jpg","modern","Animal","1","modern_a.jpg"],
["2","22","modern_h.jpg","modern","Human","2","modern_h.jpg"],
["2","22","modern_o.jpg","modern","Object","3","modern_o.jpg"],
["2","22","modern_p.jpg","modern","Plant","4","modern_p.jpg"],
["2","22","modern_r.jpg","modern","Robot","5","modern_r.jpg"],
["2","23","odd_a.jpg","odd ","Animal","1","odd_a.jpg"],
["2","23","odd_h.jpg","odd ","Human","2","odd_h.jpg"],
["2","23","odd_o.jpg","odd ","Object","3","odd_o.jpg"],
["2","23","odd_p.jpg","odd ","Plant","4","odd_p.jpg"],
["2","23","odd_r.jpg","odd ","Robot","5","odd_r.jpg"],
["2","24","okay_a.jpg","okay ","Animal","1","okay_a.jpg"],
["2","24","okay_h.jpg","okay ","Human","2","okay_h.jpg"],
["2","24","okay_o.jpg","okay ","Object","3","okay_o.jpg"],
["2","24","okay_p.jpg","okay ","Plant","4","okay_p.jpg"],
["2","24","okay_r.jpg","okay","Robot","5","okay_r.jpg"],
["2","25","old_a.jpg","old","Animal","1","old_a.jpg"],
["2","25","old_h.jpg","old ","Human","2","old_h.jpg"],
["2","25","old_o.jpg","old ","Object","3","old_o.jpg"],
["2","25","old_p.jpg","old ","Plant","4","old_p.jpg"],
["2","25","old_r.jpg","old ","Robot","5","old_r.jpg"],
["2","26","ordinary_a.jpg","ordinary ","Animal","1","ordinary_a.jpg"],
["2","26","ordinary_h.jpg","ordinary ","Human","2","ordinary_h.jpg"],
["2","26","ordinary_o.jpg","ordinary ","Object","3","ordinary_o.jpg"],
["2","26","ordinary_p.jpg","ordinary ","Plant","4","ordinary_p.jpg"],
["2","26","ordinary_r.jpg","ordinary ","Robot","5","ordinary_r.jpg"],
["2","27","peaceful_a.jpg","peaceful ","Animal","1","peaceful_a.jpg"],
["2","27","peaceful_h.jpg","peaceful ","Human","2","peaceful_h.jpg"],
["2","27","peaceful_o.jpg","peaceful ","Object","3","peaceful_o.jpg"],
["2","27","peaceful_p.jpg","peaceful ","Plant","4","peaceful_p.jpg"],
["2","27","peaceful_r.jpg","peaceful ","Robot","5","peaceful_r.jpg"],
["2","28","plain_a.jpg","plain ","Animal","1","plain_a.jpg"],
["2","28","plain_h.jpg","plain ","Human","2","plain_h.jpg"],
["2","28","plain_o.jpg","plain ","Object","3","plain_o.jpg"],
["2","28","plain_p.jpg","plain ","Plant","4","plain_p.jpg"],
["2","28","plain_r.jpg","plain ","Robot","5","plain_r.jpg"],
["2","29","quick_a.jpg","quick ","Animal","1","quick_a.jpg"],
["2","29","quick_h.jpg","quick ","Human","2","quick_h.jpg"],
["2","29","quick_o.jpg","quick ","Object","3","quick_o.jpg"],
["2","29","quick_p.jpg","quick ","Plant","4","quick_p.jpg"],
["2","29","quick_r.jpg","quick ","Robot","5","quick_r.jpg"],
["2","30","radient_a.jpg","radient ","Animal","1","radient_a.jpg"],
["2","30","radient_h.jpg","radient ","Human","2","radient_h.jpg"],
["2","30","radient_o.jpg","radient ","Object","3","radient_o.jpg"],
["2","30","radient_p.jpg","radient ","Plant","4","radient_p.jpg"],
["2","30","radient_r.jpg","radient ","Robot","5","radient_r.jpg"],
["2","31","rare_a.jpg","rare ","Animal","1","rare_a.jpg"],
["2","31","rare_h.jpg","rare ","Human","2","rare_h.jpg"],
["2","31","rare_o.jpg","rare ","Object","3","rare_o.jpg"],
["2","31","rare_p.jpg","rare ","Plant","4","rare_p.jpg"],
["2","31","rare_r.jpg","rare ","Robot","5","rare_r.jpg"],
["2","32","small_a.jpg","small ","Animal","1","small_a.jpg"],
["2","32","small_h.jpg","small ","Human","2","small_h.jpg"],
["2","32","small_o.jpg","small ","Object","3","small_o.jpg"],
["2","32","small_p.jpg","small ","Plant","4","small_p.jpg"],
["2","32","small_r.jpg","small ","Robot","5","small_r.jpg"],
["2","33","solid_a.jpg","solid ","Animal","1","solid_a.jpg"],
["2","33","solid_h.jpg","solid ","Human","2","solid_h.jpg"],
["2","33","solid_o.jpg","solid ","Object","3","solid_o.jpg"],
["2","33","solid_p.jpg","solid ","Plant","4","solid_p.jpg"],
["2","33","solid_r.jpg","solid ","Robot","5","solid_r.jpg"],
["2","34","stunning_a.jpg","stunning ","Animal","1","stunning_a.jpg"],
["2","34","stunning_h.jpg","stunning ","Human","2","stunning_h.jpg"],
["2","34","stunning_o.jpg","stunning ","Object","3","stunning_o.jpg"],
["2","34","stunning_p.jpg","stunning ","Plant","4","stunning_p.jpg"],
["2","34","stunning_r.jpg","stunning ","Robot","5","stunning_r.jpg"],
["2","35","sweet_a.jpg","sweet ","Animal","1","sweet_a.jpg"],
["2","35","sweet_h.jpg","sweet ","Human","2","sweet_h.jpg"],
["2","35","sweet_o.jpg","sweet ","Object","3","sweet_o.jpg"],
["2","35","sweet_p.jpg","sweet ","Plant","4","sweet_p.jpg"],
["2","35","sweet_r.jpg","sweet ","Robot","5","sweet_r.jpg"],
["2","36","tall_a.jpg","tall ","Animal","1","tall_a.jpg"],
["2","36","tall_h.jpg","tall ","Human","2","tall_h.jpg"],
["2","36","tall_o.jpg","tall ","Object","3","tall_o.jpg"],
["2","36","tall_p.jpg","tall ","Plant","4","tall_p.jpg"],
["2","36","tall_r.jpg","tall ","Robot","5","tall_r.jpg"],
["2","37","ugly_a.jpg","ugly ","Animal","1","ugly_a.jpg"],
["2","37","ugly_h.jpg","ugly ","Human","2","ugly_h.jpg"],
["2","37","ugly_o.jpg","ugly ","Object","3","ugly_o.jpg"],
["2","37","ugly_p.jpg","ugly ","Plant","4","ugly_p.jpg"],
["2","37","ugly_r.jpg","ugly ","Robot","5","ugly_r.jpg"],
["2","38","weird_a.jpg","weird ","Animal","1","weird_a.jpg"],
["2","38","weird_h.jpg","weird ","Human","2","weird_h.jpg"],
["2","38","weird_o.jpg","weird ","Object","3","weird_o.jpg"],
["2","38","weird_p.jpg","weird ","Plant","4","weird_p.jpg"],
["2","38","weird_r.jpg","weird ","Robot","5","weird_r.jpg"],
["2","39","wild_a.jpg","wild","Animal","1","wild_a.jpg"],
["2","39","wild_h.jpg","wild","Human","2","wild_h.jpg"],
["2","39","wild_o.jpg","wild","Object","3","wild_o.jpg"],
["2","39","wild_p.jpg","wild","Plant","4","wild_p.jpg"],
["2","39","wild_r.jpg","wild","Robot","5","wild_r.jpg"],
["2","40","wonderful_a.jpg","wonderful ","Animal","1","wonderful_a.jpg"],
["2","40","wonderful_h.jpg","wonderful ","Human","2","wonderful_h.jpg"],
["2","40","wonderful_o.jpg","wonderful ","Object","3","wonderful_o.jpg"],
["2","40","wonderful_p.jpg","wonderful ","Plant","4","wonderful_p.jpg"],
["2","40","wonderful_r.jpg","wonderful ","Robot","5","wonderful_r.jpg"],
["2","41","aggressive.jpg","aggressive","word","6","aggressive.jpg"],
["2","42","amazing.jpg","amazing","word","6","amazing.jpg"],
["2","43","anxious.jpg","anxious","word","6","anxious.jpg"],
["2","44","awesome.jpg","awesome","word","6","awesome.jpg"],
["2","45","basic.jpg","basic","word","6","basic.jpg"],
["2","46","classic.jpg","classic","word","6","classic.jpg"],
["2","47","cool.jpg","cool","word","6","cool.jpg"],
["2","48","cute.jpg","cute","word","6","cute.jpg"],
["2","49","extraordinairy.jpg","extraordinairy","word","6","extraordinairy.jpg"],
["2","50","fair.jpg","fair","word","6","fair.jpg"],
["2","51","good.jpg","good","word","6","good.jpg"],
["2","52","great.jpg","great","word","6","great.jpg"],
["2","53","handsome.jpg","handsome","word","6","handsome.jpg"],
["2","54","heavy.jpg","heavy","word","6","heavy.jpg"],
["2","55","hot.jpg","hot","word","6","hot.jpg"],
["2","56","huge.jpg","huge","word","6","huge.jpg"],
["2","57","ideal.jpg","ideal","word","6","ideal.jpg"],
["2","58","impressive.jpg","impressive","word","6","impressive.jpg"],
["2","59","interesting.jpg","interesting","word","6","interesting.jpg"],
["2","80","wonderful.jpg","wonderful","word","6","wonderful.jpg"],
["2","81","filler1-k.jpg","filler","question","7","filler1-k.jpg"],
["2","82","filler2-k.jpg","filler","question","7","filler2-k.jpg"],
["2","83","filler3-k.jpg","filler","question","7","filler3-k.jpg"],
["2","84","filler4-k.jpg","filler","question","7","filler4-k.jpg"],
["2","85","filler5-k.jpg","filler","question","7","filler5-k.jpg"]
];


var AllDataSources = [DataSourceA,DataSourceB];
