var DataSourceA = [
["1","1","1","Congruent","John eats pizza every Sunday","Pizza","1_S.png","1.1_F.png"],
["1","4","1","Congruent","I missed the train!","Train","4_S.png","4.1_F.png"],
["1","7","1","Congruent","Man, she's one hell of an artist","Singing","7_S.png","7.1_F.png"],
["1","10","1","Congruent","Want to go grab a cup of coffee?","Coffee","10_S.png","10.1_F.png"],
["1","13","1","Congruent","She bathes like 4 times a week, man.","Bath","13_S.png","1.3_F.png"],
["1","16","1","Congruent","He refuses to read that part of the book","Books","16_S.png","4.3_F.png"],
["1","19","1","Congruent","You want to go sailing? Good luck!","Boat","19_S.png","7.3_F.png"],
["1","22","1","Congruent","I'd adopt a cat with you","Dog","22_S.png","10.3_F.png"],
["1","3","2","Elaborative","Your crush is coming to the party!","Party","3_S.png","3.2_F.png"],
["1","6","2","Elaborative","I have class till 5pm today","Time","6_S.png","6.2_F.png"],
["1","9","2","Elaborative","Someone is wearing perfume, I can smell it.","Smell","9_S.png","9.2_F.png"],
["1","12","2","Elaborative","I may have had a drink or two..","Drinking","12_S.png","12.2_F.png"],
["1","15","2","Elaborative","You want a piece of that Kiwi, don't you?","Kiwi","15_S.png","3.2_F.png"],
["1","18","2","Elaborative","I'm going skiing, so I won't be at your party","Skiing","18_S.png","6.2_F.png"],
["1","21","2","Elaborative","You like grapes?","Grapes","21_S.png","9.2_F.png"],
["1","24","2","Elaborative","It's late and I can't find my keys","","24_S.png","12.2_F.png"],
["1","2","3","Incongruent","I'm having dinner with my family","Dinner","2_S.png","2.3_F.png"],
["1","5","3","Incongruent","I saw Stacy's dog today!","Dog","5_S.png","5.3_F.png"],
["1","8","3","Incongruent","That's great! Terrific!","Positive?","8_S.png","8.3_F.png"],
["1","11","3","Incongruent","She fell down the stairs while texting him!","Injury","11_S.png","11.3_F.png"],
["1","14","3","Incongruent","My sister still sleeps with that unicorn","Unicorn","14_S.png","2.1_F.png"],
["1","17","3","Incongruent","Did you hear her voice?","Voice","17_S.png","5.1_F.png"],
["1","20","3","Incongruent","Mom wasn't too happy I went to bed at 4am yesterday","Bedtime","20_S.png","8.1_F.png"],
["1","23","3","Incongruent","He's a real winner, right?","","23_S.png","11.1_F.png"],
];

var DataSourceB = [
["2","2","1","Congruent","I'm having dinner with my family","Dinner","2_S.png","2.1_F.png"],
["2","5","1","Congruent","I saw Stacy's dog today!","Dog","5_S.png","5.1_F.png"],
["2","8","1","Congruent","That's great! Terrific!","Positive?","8_S.png","8.1_F.png"],
["2","11","1","Congruent","She fell down the stairs while texting him!","Injury","11_S.png","11.1_F.png"],
["2","14","1","Congruent","My sister still sleeps with that unicorn","Unicorn","14_S.png","2.3_F.png"],
["2","17","1","Congruent","Did you hear her voice?","Voice","17_S.png","5.3_F.png"],
["2","20","1","Congruent","Mom wasn't too happy I went to bed at 4am yesterday","Bedtime","20_S.png","8.3_F.png"],
["2","23","1","Congruent","He's a real winner, right?","","23_S.png","11.3_F.png"],
["2","1","2","Elaborative","John eats pizza every Sunday","Pizza","1_S.png","1.2_F.png"],
["2","4","2","Elaborative","I missed the train!","Train","4_S.png","4.2_F.png"],
["2","7","2","Elaborative","Man, she's one hell of an artist","Singing","7_S.png","7.2_F.png"],
["2","10","2","Elaborative","Want to go grab a cup of coffee?","Coffee","10_S.png","10.2_F.png"],
["2","13","2","Elaborative","She bathes like 4 times a week, man.","Bath","13_S.png","1.2_F.png"],
["2","16","2","Elaborative","He refuses to read that part of the book","Books","16_S.png","4.2_F.png"],
["2","19","2","Elaborative","You want to go sailing? Good luck!","Boat","19_S.png","7.2_F.png"],
["2","22","2","Elaborative","I'd adopt a cat with you","Dog","22_S.png","10.2_F.png"],
["2","3","3","Incongruent","Your crush is coming to the party!","Party","3_S.png","3.3_F.png"],
["2","6","3","Incongruent","I have class till 5pm today","Time","6_S.png","6.3_F.png"],
["2","9","3","Incongruent","Someone is wearing perfume, I can smell it.","Smell","9_S.png","9.3_F.png"],
["2","12","3","Incongruent","I may have had a drink or two..","Drinking","12_S.png","12.3_F.png"],
["2","15","3","Incongruent","You want a piece of that Kiwi, don't you?","Kiwi","15_S.png","3.1_F.png"],
["2","18","3","Incongruent","I'm going skiing, so I won't be at your party","Skiing","18_S.png","6.1_F.png"],
["2","21","3","Incongruent","You like grapes?","Grapes","21_S.png","9.1_F.png"],
["2","24","3","Incongruent","It's late and I can't find my keys","","24_S.png","12.1_F.png"],
];

var DataSourceC = [
["3","3","1","Congruent","Your crush is coming to the party!","Party","3_S.png","3.1_F.png"],
["3","6","1","Congruent","I have class till 5pm today","Time","6_S.png","6.1_F.png"],
["3","9","1","Congruent","Someone is wearing perfume, I can smell it.","Smell","9_S.png","9.1_F.png"],
["3","12","1","Congruent","I may have had a drink or two..","Drinking","12_S.png","12.1_F.png"],
["3","15","1","Congruent","You want a piece of that Kiwi, don't you?","Kiwi","15_S.png","3.3_F.png"],
["3","18","1","Congruent","I'm going skiing, so I won't be at your party","Skiing","18_S.png","6.3_F.png"],
["3","21","1","Congruent","You like grapes?","Grapes","21_S.png","9.3_F.png"],
["3","24","1","Congruent","It's late and I can't find my keys","","24_S.png","12.3_F.png"],
["3","2","2","Elaborative","I'm having dinner with my family","Dinner","2_S.png","2.2_F.png"],
["3","5","2","Elaborative","I saw Stacy's dog today!","Dog","5_S.png","5.2_F.png"],
["3","8","2","Elaborative","That's great! Terrific!","Positive?","8_S.png","8.2_F.png"],
["3","11","2","Elaborative","She fell down the stairs while texting him!","Injury","11_S.png","11.2_F.png"],
["3","14","2","Elaborative","My sister still sleeps with that unicorn","Unicorn","14_S.png","2.2_F.png"],
["3","17","2","Elaborative","Did you hear her voice?","Voice","17_S.png","5.2_F.png"],
["3","20","2","Elaborative","Mom wasn't too happy I went to bed at 4am yesterday","Bedtime","20_S.png","8.2_F.png"],
["3","23","2","Elaborative","He's a real winner, right?","","23_S.png","11.2_F.png"],
["3","1","3","Incongruent","John eats pizza every Sunday","Pizza","1_S.png","1.3_F.png"],
["3","4","3","Incongruent","I missed the train!","Train","4_S.png","4.3_F.png"],
["3","7","3","Incongruent","Man, she's one hell of an artist","Singing","7_S.png","7.3_F.png"],
["3","10","3","Incongruent","Want to go grab a cup of coffee?","Coffee","10_S.png","10.3_F.png"],
["3","13","3","Incongruent","She bathes like 4 times a week, man.","Bath","13_S.png","1.1_F.png"],
["3","16","3","Incongruent","He refuses to read that part of the book","Books","16_S.png","4.1_F.png"],
["3","19","3","Incongruent","You want to go sailing? Good luck!","Boat","19_S.png","7.1_F.png"],
["3","22","3","Incongruent","I'd adopt a cat with you","Dog","22_S.png","10.1_F.png"]
];

var AllDataSources=[DataSourceA,DataSourceB,DataSourceC];